server:
  port: 8080

jwt:
  secret: hello.world.ee.ff

# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/capstonedesign_db?useSSL=false&serverTimezone=Asia/Seoul&allowPubliKeyRetrieval=true&characterEncoding=UTF-8
    username: capstonedesign_user
    password: Hhs2684021@!@
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  # spring data jpa 설정
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
